<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<NorseRef Include="Infrastructure.Persistence.EntityFramework">
			<Repo>Midgard</Repo>
		</NorseRef>
		<PackageReference Include="Testcontainers.PostgreSql" Version="*" />
		<ProjectReference Include="../../src/Reference.Web.Server/Reference.Web.Server.csproj" />
	</ItemGroup>
</Project>
