<Project Sdk="Microsoft.NET.Sdk.Razor">
	<ItemGroup>
		<!-- Fix for: https://github.com/bUnit-dev/bUnit/issues/1872 -->
		<PackageReference Include="AngleSharp" Version="*" />
		<PackageReference Include="bunit" Version="*" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="11.*-*" />
		<ProjectReference Include="../../src/Reference.Components/Reference.Components.csproj" />
	</ItemGroup>
</Project>
